// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2_zZ_KjOHjUnItiT8Q5nnHCQc8LFx0Mg',
    appId: '1:534236766904:web:bf2295daa0807cd6b70a4d',
    messagingSenderId: '534236766904',
    projectId: 'customerapp-ed594',
    authDomain: 'customerapp-ed594.firebaseapp.com',
    storageBucket: 'customerapp-ed594.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBymro3CJt9eMx92_HwfwJDMUeNdNNRFBo',
    appId: '1:534236766904:android:0aeea8235ee8be5ab70a4d',
    messagingSenderId: '534236766904',
    projectId: 'customerapp-ed594',
    storageBucket: 'customerapp-ed594.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQXRQ9HcEcIB5F4ea72dwRQRJrwd-KZuQ',
    appId: '1:534236766904:ios:f989b10da0b170deb70a4d',
    messagingSenderId: '534236766904',
    projectId: 'customerapp-ed594',
    storageBucket: 'customerapp-ed594.appspot.com',
    iosBundleId: 'com.example.customerApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQXRQ9HcEcIB5F4ea72dwRQRJrwd-KZuQ',
    appId: '1:534236766904:ios:f989b10da0b170deb70a4d',
    messagingSenderId: '534236766904',
    projectId: 'customerapp-ed594',
    storageBucket: 'customerapp-ed594.appspot.com',
    iosBundleId: 'com.example.customerApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2_zZ_KjOHjUnItiT8Q5nnHCQc8LFx0Mg',
    appId: '1:534236766904:web:1ae135d49923fa7cb70a4d',
    messagingSenderId: '534236766904',
    projectId: 'customerapp-ed594',
    authDomain: 'customerapp-ed594.firebaseapp.com',
    storageBucket: 'customerapp-ed594.appspot.com',
  );
}
